DROP DATABASE IF EXISTS DBVACINAVILMAR;

CREATE DATABASE DBVACINAVILMAR;

USE DBVACINAVILMAR;

CREATE TABLE PESSOA (
	IDPESSOA INT NOT NULL AUTO_INCREMENT
    , NOME VARCHAR(200) NOT NULL
    , DATA_NASCIMENTO DATE NULL
    , SEXO CHAR(1) NOT NULL
    , CPF VARCHAR(11) NOT NULL UNIQUE
    , TIPO ENUM('PESQUISADOR', 'PACIENTE') NOT NULL
    , CONSTRAINT PK_PESSOA PRIMARY KEY (IDPESSOA)
);

CREATE TABLE VACINA (
	IDVACINA INT NOT NULL AUTO_INCREMENT
    , NOME VARCHAR(200) NOT NULL
    , PAIS_ORIGEM VARCHAR(100) NOT NULL
    , ESTAGIO_PESQUISA ENUM('INICIAL', 'TESTES', 'APLICACAO_MASSIVA') NOT NULL
    , DATA_INICIO_PESQUISA DATE NOT NULL
    , ID_PESQUISADOR_RESPONSAVEL INT NOT NULL
    , FASE ENUM('SOMENTE_PESQUISADOR', 'VOLUNTARIO', 'PUBLICO_GERAL') NOT NULL
    , QUANTIDADE_DOSES INT NOT NULL
    , CONSTRAINT PK_VACINA PRIMARY KEY (IDVACINA)
    , CONSTRAINT FK_VACINA_PESSOA FOREIGN KEY (ID_PESQUISADOR_RESPONSAVEL) REFERENCES PESSOA (IDPESSOA)
);

CREATE TABLE APLICACAO_VACINA (
	ID_APLICACAO_VACINA INT NOT NULL AUTO_INCREMENT
    , IDVACINA INT NOT NULL
    , IDPESSOA INT NOT NULL
    , DATA_APLICACAO DATE NOT NULL
    , NOTA ENUM('PESSIMO', 'RUIM', 'REGULAR', 'BOM', 'OTIMO') NOT NULL
    , CONSTRAINT PK_APLICACAO_VACINA_PESSOA PRIMARY KEY (ID_APLICACAO_VACINA)
    , CONSTRAINT FK_APLICACAO_VACINA__VACINA FOREIGN KEY (IDVACINA) REFERENCES VACINA (IDVACINA)
    , CONSTRAINT FK_APLICACAO_PESSOA FOREIGN KEY (IDPESSOA) REFERENCES PESSOA (IDPESSOA)
);

-- PESSOA
INSERT INTO PESSOA (NOME, DATA_NASCIMENTO, SEXO, CPF, TIPO) 
	       VALUES ("ALBERTO", '1999-09-25', 'M', "4672890239", "PESQUISADOR");
INSERT INTO PESSOA (NOME, DATA_NASCIMENTO, SEXO, CPF, TIPO) 
		   VALUES ("ANA", '1985-02-20', 'F', "375023894", "PACIENTE");

-- VACINA
INSERT INTO VACINA (NOME, PAIS_ORIGEM, ESTAGIO_PESQUISA, DATA_INICIO_PESQUISA, ID_PESQUISADOR_RESPONSAVEL, FASE, QUANTIDADE_DOSES)
VALUES ("VAC 1", "BRA", "INICIAL", '2020-05-19', 1, "SOMENTE_PESQUISADOR", 2);
INSERT INTO VACINA (NOME, PAIS_ORIGEM, ESTAGIO_PESQUISA, DATA_INICIO_PESQUISA, ID_PESQUISADOR_RESPONSAVEL, FASE, QUANTIDADE_DOSES)
VALUES ("VAC 2", "ARG", "TESTES", '2020-11-12', 2, "VOLUNTARIO", 2);

-- APLICACAO VACINA
INSERT INTO APLICACAO_VACINA (IDVACINA, IDPESSOA, DATA_APLICACAO, NOTA)
	VALUES (1, 2, '2020-11-29', "REGULAR");
INSERT INTO APLICACAO_VACINA (IDVACINA, IDPESSOA, DATA_APLICACAO, NOTA)
	VALUES (2, 1, '2020-06-12', "OTIMO");

SELECT * FROM PESSOA;

SELECT * FROM VACINA;

SELECT * FROM APLICACAO_VACINA;

SELECT * FROM VACINA WHERE UPPER(NOME) = "VAC 1" AND UPPER(pais_origem) = "BRA";